---
- name: change permissions of the file is an empty file
  hosts: all
  tasks:
    - name: capture file info
      stat: 
        path: /tmp/newfile
      register: result
    - name: Display ouyput of the above module
      debug:
        var: result
    - name: change permission if the file is empty
      file:
        name: /tmp/newfile
        mode: 770
      when: result.stat.size == 0
