---
- name: Implementing global scope variables
  hosts: all
  tasks: 
    - name: Install/Uninstall s/w app's
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...      
