---
- name: install git on all servers and remote git repo
  hosts: all
  tasks:
    - name: install git on all servers
      apt:
        name: git
        state: present
        update_cache: yes
    - name: clone remote github repo
      git:
        repo: https://github.com/intelliqittrainings/maven.git
        dest: /tmp/newit
...          
