---
- name: check if f1 directory is present if not create a file f1
  hosts: all
  tasks:
    - name: check for f1 directory
      stat: 
        path: /home/ubuntu/f1
      register: a
    - name: print output of the above modules
      debug:
        var: a
    - name: create file f1 if is not present 
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
